#!/usr/bin/env python3
"""Turn verified SSP kirtanas into SQL for the library.

    python3 tools/build-ssp.py --emit tools/data/ssp.json
    python3 tools/load-ssp.py tools/data/ssp.json > tools/data/ssp.sql

Only what `--emit` wrote is loaded, and `--emit` only writes kirtanas whose
every section lasts a whole number of avartanas against the tala the book
prints for it.

Two things are decided here rather than in the extractor.

Svaras are stored as the book prints them: bare letters. SSP writes S R G M P
D N and leaves the variant to the ragam, as a reader is expected to know it,
and elsewhere the library stores the variant spelled out (D2, G3). Resolving
one to the other means reading it off the ragam's scale, which is
unambiguous for most ragams and not for a bhashanga raga using two variants
of the same letter. Rather than guess in those cases, or silently mix
resolved and unresolved notation, this keeps what the source actually says.

And a kirtana is attached to an existing library row when the title and the
ragam both agree, so that SSP fills in notation for a kriti already listed
rather than creating a second copy of it.
"""

import json
import math
import os
import sys
import unicodedata
import re
import importlib.util

_here = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location("tala", os.path.join(_here, "lib", "tala.py"))
tala = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(tala)

SOURCE = "ssp:1904"
LICENSE = ("public domain — Subbarama Dikshitar, Sangita Sampradaya Pradarsini, "
           "1904 · notation extracted from the English web edition "
           "(typesetting © Guruguhanugraha Archives)")
URL = "http://ibiblio.org/guruguha/"

SECTION_TITLE = {"pallavi": "Pallavi", "anupallavi": "Anupallavi",
                 "caranam": "Caranam", "carana": "Caranam",
                 "madhyamakala": "Madhyamakala", "cittasvara": "Chittasvaram",
                 "muktayisvara": "Muktayisvaram", "samasticaranam": "Samashti Caranam",
                 "_": "Notation"}


def deaccent(t):
    t = unicodedata.normalize("NFD", t or "")
    return "".join(c for c in t if not unicodedata.combining(c))


def clean_name(t):
    """Readable form of a name SSP set without spaces between words."""
    t = deaccent(t).replace("ı", "i")
    t = re.sub(r"([a-z])([A-Z])", r"\1 \2", t)
    return t.strip()


def grid_factor(sections):
    """How finely the piece is divided, as a whole-number multiplier.

    SSP halves and quarters aksharas with its underlines, so a duration can be
    0.5 or 0.25. The library renders a note as one cell plus a comma for every
    further akshara it holds, which only works on whole numbers. Scaling the
    whole piece by the smallest common unit keeps the arithmetic exact and
    makes the subdivision visible the way it is on the page: at a factor of
    two, a full akshara is "S ," and a half is "S".
    """
    from fractions import Fraction
    den = 1
    for s in sections:
        for n in s["notes"]:
            if n.get("grace"):
                continue
            f = Fraction(n["d"]).limit_denominator(64)
            den = den * f.denominator // __import__("math").gcd(den, f.denominator)
    return den


def kalai_of(sections, cycle):
    """The kalai at which every section comes out whole."""
    for k in (1, 2, 4):
        if all(abs(s["aksharas"] / (cycle * k) - round(s["aksharas"] / (cycle * k))) < 1e-6
               and round(s["aksharas"] / (cycle * k)) >= 1 for s in sections):
            return k
    return 1


def display_tala(name):
    """The tala string the library's renderer can look up.

    Anga bar lines are drawn by matching this against the app's tala picker,
    which spells them "Khanda Triputa - 9 beats" and accepts a common name in
    brackets. A descriptive name of our own gets no bars.
    """
    lab = tala.engine_label(name)
    if tala.family(name) == "adi" or ("adi" in name and "jati" not in name):
        return "Adi"
    if lab and lab.startswith("Chaturasra Eka"):
        return "Chaturasra Eka"
    if not lab and "capu" in name:
        return "Khanda Chapu" if "khanda" in name else clean_name(name)
    return lab or clean_name(name)


def q(v):
    if v is None:
        return "null"
    return "'" + str(v).replace("'", "''") + "'"


def main():
    src = json.load(open(sys.argv[1], encoding="utf-8"))
    part = sys.argv[2] if len(sys.argv) > 2 else "all"
    out = []
    add = out.append

    add("-- Verified kirtanas from the Sangita Sampradaya Pradarsini (1904).")
    add("-- Generated by tools/load-ssp.py; see tools/build-ssp.py --audit.")
    add("""
drop table if exists ssp_in;
create table ssp_in (
  num text, title text, ragam text, tala text, composer text,
  page int, printed_page int, cycle int, kalai int,
  complete boolean, notation jsonb, flat text, sections int, sahitya boolean
);
""")

    for kr in src:
        cycle = sum(kr["anga"])
        kalai = kalai_of(kr["sections"], cycle)
        names = [s["name"] for s in kr["sections"]]
        complete = ("pallavi" in names and "anupallavi" in names
                    and any(n.startswith("caran") for n in names))
        factor = grid_factor(kr["sections"])
        apc = cycle * kalai * factor
        secs, flat = [], []
        for s in kr["sections"]:
            svaras, units, octs, syl = [], 0, set(), False
            for n in s["notes"]:
                if n.get("grace"):
                    continue          # ornament, not an akshara of the line
                # Whole units: the renderer draws a note as one cell plus a
                # comma per further akshara held, which needs integers.
                from fractions import Fraction
                d = max(1, int(round(Fraction(n["d"]).limit_denominator(64) * factor)))
                sv = {"s": n["s"], "o": n["o"], "d": d}
                if n.get("syl"):
                    sv["syl"] = n["syl"]
                    syl = True
                if n.get("gamaka"):
                    sv["gamaka"] = n["gamaka"]
                svaras.append(sv)
                units += d
                octs.add(n["o"])
                flat.append(n["s"] + ("'" * n["o"] if n["o"] > 0 else "." * -n["o"]))
            secs.append({"name": SECTION_TITLE.get(s["name"], s["name"].title()),
                         "svaras": svaras, "aksharas": units,
                         "cycles": round(units / apc, 2) if apc else None,
                         "octaves": sorted(octs), "sahitya": syl})
        shown = display_tala(kr["tala"])
        notation = {
            "tala": shown,
            "aksharasPerCycle": apc,
            "gridFactor": factor,
            "sections": secs,
            "provenance": {
                "source": SOURCE, "piece": kr["number"], "volume": "cakram 1-4",
                "page": kr["printed_page"], "pdf_page": kr["page"],
                "kalai": kalai, "aksharasPerAvartana": cycle,
                "verified": "every section is a whole number of avartanas "
                            "against the printed tala",
            },
        }
        has_syl = any(x["sahitya"] for x in secs)
        add("insert into ssp_in values (%s,%s,%s,%s,%s,%d,%s,%d,%d,%s,%s::jsonb,%s,%d,%s);"
            % (q(kr["number"]), q(kr["title"]), q(clean_name(kr["ragam"])),
               q(shown), q(clean_name(kr["composer"])),
               kr["page"], kr["printed_page"] if kr["printed_page"] else "null",
               cycle, kalai, "true" if complete else "false",
               q(json.dumps(notation, ensure_ascii=False)),
               q(" ".join(flat)), len(secs), "true" if has_syl else "false"))

    add("""
-- Attach to the kriti already in the library when title AND ragam agree.
alter table ssp_in add column kriti uuid;
update ssp_in i set kriti = k.id
from kritis k
where left(phon(k.title),11) = left(phon(i.title),11)
  and length(phon(k.title)) >= 8
  and phon(k.ragam) = phon(i.ragam);

-- Anything with no counterpart becomes a new row.
insert into kritis (title, composer, ragam, tala, form, source, license, source_url, notes)
select initcap(i.title), i.composer, i.ragam, i.tala, 'Kirtana',
       %s, %s, %s,
       'Sangita Sampradaya Pradarsini ' || i.num || ', printed page ' || coalesce(i.printed_page::text,'?')
from ssp_in i where i.kriti is null;

update ssp_in i set kriti = k.id
from kritis k
where i.kriti is null and k.source = %s
  and phon(k.title) = phon(i.title);

insert into versions (kriti_id, contributor, note, notation, flat, status,
                      sections, has_sahitya, octaves)
select i.kriti, 'Subbarama Dikshitar (1904)',
       'Sangita Sampradaya Pradarsini ' || i.num ||
       ', printed page ' || coalesce(i.printed_page::text,'?') ||
       ' — ' || i.kalai || ' kalai, ' || i.cycle || ' aksharas per avartana',
       i.notation, i.flat, 'seed', i.sections, i.sahitya, 'as printed'
from ssp_in i where i.kriti is not null;

-- completeness is not set here. The library computes it from the version by
-- its own rule -- more than one section, with sahitya -- in a trigger that
-- fires on insert, and that rule is what every other source in the table was
-- judged by. An earlier version of this file imposed a stricter one of its
-- own (pallavi AND anupallavi AND caranam) and marked fifteen kirtanas
-- partial that the library counts as complete. Checked against the book: all
-- 26 carry exactly the sections SSP prints for them, and the ones with two
-- have only two on the page.
""" % (q(SOURCE), q(LICENSE), q(URL), q(SOURCE)))
    add("drop table ssp_in;")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
